version: '3'

services:
  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - .:/code
    ports:
      - 8000:8000
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_DB=${DB_NAME}
#       - POSTGRES_USER=${USER_NAME}
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
